name: Build and Deploy
on: 
  push:
    branches: [ deploy ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout code
    - name: checkout 
      uses: actions/checkout@v3

    - name: setup 
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # Install and build
    - name: Install and Build
      run: |
        npm install
        npm run build

    # Deploy to server  
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v2
      with:
        branch: gh-pages
        # 打包後創建的資料夾名稱
        folder: dist